language: objective-c
osx_image: xcode9.4
branches:
  only:
    - master

before_install:
  - bundle install
  - pod install --repo-update
  
script:
  - set -o pipefail
  - fastlane travis
  - pod lib lint --quick

notifications:
  email:
    recipients:
      - bas@e-sites.nl
    on_success: never
    on_failure: always