language: objective-c
osx_image: xcode9.4

script:
  - bundle install
  - bundle exec pod install --repo-update
  - xcodebuild -workspace ProntoSDK.xcworkspace -scheme ProntoSDK -configuration Debug -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone 8' clean build test
