language: objective-c
osx_image: xcode9.4
branches:
  only:
    - master

cache: bundler

before_install:
  - bundle install
  - pod install --repo-update
  
script:
  - set -o pipefail
  - pod lib lint --quick
  - fastlane travis

notifications:
  email:
    recipients:
      - bas@e-sites.nl
    on_success: never
    on_failure: always
  slack:  
    rooms:
      - pronto-am:oF0mkHg2sYBLgcT6Rxn2iUzv#builds
    on_success: never
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)