fastlane_version "2.98.0"

default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :travis do
    swiftlint

    # Run tests (iOS)
    scan(
      scheme: "ProntoSDK",
      project: "ProntoSDK.xcodeproj",
      device: "iPhone 8",
      code_coverage: true
    )
  end
end
