fastlane_version "2.98.0"

default_platform :ios

platform :ios do

  desc "Runs all the tests"
  lane :travis do
    workspace = "ProntoSDK.xcworkspace"

    # Run tests (iOS)
    scheme = "ProntoSDK"
    scan(
      scheme: scheme,
      workspace: workspace,
      device: "iPhone 8",
      code_coverage: true
    )
  end
end
